### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by devtronic** [mintware-de/flutter_barcode_reader#187]
Any ideas how can we achieve a dynamic scanner view? 

- Use a Flutter view which gets the current preview image + meta information where detected barcodes are located to render the view directly in flutter. (idk about performance)
- Pass layout options to the BarcodeScanner.scan() method.
- Overlay the platform screen with a flutter screen which renders the overlay UI

This issue belongs to:
- [ ] [#273 Can we remove the scanning box from the center of the screen?](273)
- [ ] [#265 The title in the app bar should be controlled by the strings option](265)
- [ ] [#223 Allow to change reader width](223)
- [ ] [#196 Configuring scan area](196)
- [ ] [#188 UI customization](188)
- [ ] [#179 Change design](179)
- [ ] [#158 How to tweak the look of the scanner?](158)
- [ ] [#152 Request - Camera outline ratio](152)
- [ ] [#143 Scan QRCode Customer View?](143)
- [ ] [#77 Scanning outside the "window" on iOS](77)
- [ ] [#69 The transition is not smooth](69)
- [ ] [#66 Scan line color](66)
- [ ] [#43 Ability to highlight the barcode in live view and allow user to tap on desired barcode](43)

**Comment by wesguirra** [comment]
Use a Flutter view which gets the current preview image + meta information where detected barcodes are located to render the view directly in flutter. (idk about performance) +1

**Comment by phcaraujo** [comment]
From what I saw then, will it not be possible to change the design, even in future versions?

**Comment by devtronic** [comment]
It's just a definition thing. We need to determine what should be customizable by devs and implement this feature.

**Comment by tobyarevalo** [comment]
The default Ui from the scanner doesn´t matches the Ui from my app, i really need to change it.
Try to make it custom!

**Comment by cahyowhy** [comment]
thanks for this lib, its awesome
could you give me some reference about this..
about how to render flutter view inside the camera while scan the barcode

**Comment by vitorzarzar** [comment]
The best approach i've seen was the lib returning a Widget, so the dev could put anything on top of it (with Stack) without any need of implementation from the lib side.

As example, there is the [qr_code_scanner](https://pub.dev/packages/qr_code_scanner)

I'm new with Flutter and mobile development, so i may be saying something wrong, just tried to help.

**Comment by subinsv** [comment]
Hi. Thanks for this awesome library.

Is it possible to remove the AppBar in Android when in scannerview?

**Comment by devtronic** [comment]
Maybe native views are a good solution for customizing the UI? https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6

**Comment by alexnaldo** [comment]
The barcode reads function is great, but without UI customization is very hard to adopt it. UI is essential feature for Flutter users.

**Comment by subinsv** [comment]
@devtronic From the article
> Embedding Android views is an expensive operation and should be avoided when a Flutter equivalent is possible.

So, it is a choice between customization and performance.

**Comment by devtronic** [comment]
> @devtronic From the article
> 
> > Embedding Android views is an expensive operation and should be avoided when a Flutter equivalent is possible.
> 
> So, it is a choice between customization and performance.

Yes, we've to evaluate what brings a better performance:
- Using a Native View for the camera preview or
- passing the raw image through a platform channel to render it directly in flutter

Never the less, this would be an optional feature like `scanWithCustomPreview(...)` or something else so we don't have to force the users to implement their own preview

**Comment by alexnaldo** [comment]
Another option is pass parameters for easy customizations like view size, colors, alignment etc.

**Comment by AlisonLopes** [comment]
Make it responsive when changing screen orientation  portrait / landscape

**Comment by saddemYassin** [comment]
I want only to remove the app bar from the default view. Are they any available solution? 
![Screenshot_20200423-144618](https://user-images.githubusercontent.com/10330054/80106819-a0e3a800-857a-11ea-8ccb-eb53984411d5.jpg)

**Comment by alexnaldo** [comment]
@saddem123 , you can edit the sources (iOS e Android). Remember that this component is a wrapper

**Comment by saddemYassin** [comment]
@alexnaldo  what you mean by change the sources I just import the library in flutter how to edit it?

**Comment by Axort** [comment]
@saddem123 You can fork this library, make the changes you need and then point to your fork in the pubspec.yaml, e.g.
```
barcode_scan:
    git: 
      url: [your_fork]
```

**Comment by devtronic** [comment]
> I want only to remove the app bar from the default view. Are they any available solution?

What's about the flash button? If there is no app bar you can't toggle the flash.

**Comment by daveparks23** [comment]
Pretty simple to change the color of the text in the App Bar in iOS
**BarScannerViewControllerSwift**
Color of text Flash On / Flash Off
```
private func updateToggleFlashButton() {
    if !hasTorch {
      return
    }
    
    let buttonText = isFlashOn ? config.strings["flash_off"] : config.strings["flash_on"]

    let customRightBarButtonItem = UIBarButtonItem(title: buttonText,
                                                        style: .plain,
                                                        target: self,
                                                        action: #selector(onToggleFlash)
    )
    customRightBarButtonItem.tintColor = UIColor.orange
    navigationItem.rightBarButtonItem = customRightBarButtonItem
    
  }
```

**ScannerOverlay.swift**
Corner line color orange
```
override init(frame: CGRect) {
        super.init(frame: frame)
        line.backgroundColor = UIColor.orange
        line.translatesAutoresizingMaskIntoConstraints = false
        
        addSubview(line)
    }
```

Scanner line color orange
At the end of the draw function inside ScannerOverlay.swift file
```
path.lineWidth = 2
UIColor.orange.setStroke()
path.stroke()
```

Can someone show me where the code is for the Android-related color options?  I can't find it.

**Comment by webberlin0933** [comment]
> Pretty simple to change the color of the text in the App Bar in iOS
> **BarScannerViewControllerSwift**
> Color of text Flash On / Flash Off
> 
> ```
> private func updateToggleFlashButton() {
>     if !hasTorch {
>       return
>     }
>     
>     let buttonText = isFlashOn ? config.strings["flash_off"] : config.strings["flash_on"]
> 
>     let customRightBarButtonItem = UIBarButtonItem(title: buttonText,
>                                                         style: .plain,
>                                                         target: self,
>                                                         action: #selector(onToggleFlash)
>     )
>     customRightBarButtonItem.tintColor = UIColor.orange
>     navigationItem.rightBarButtonItem = customRightBarButtonItem
>     
>   }
> ```
> 
> **ScannerOverlay.swift**
> Corner line color orange
> 
> ```
> override init(frame: CGRect) {
>         super.init(frame: frame)
>         line.backgroundColor = UIColor.orange
>         line.translatesAutoresizingMaskIntoConstraints = false
>         
>         addSubview(line)
>     }
> ```
> 
> Scanner line color orange
> At the end of the draw function inside ScannerOverlay.swift file
> 
> ```
> path.lineWidth = 2
> UIColor.orange.setStroke()
> path.stroke()
> ```
> 
> Can someone show me where the code is for the Android-related color options? I can't find it.

I have the similar problem.I want to add a straight line to make it point to the center when scanning.
This requirement stems from the fact that when scanninng, the center point needs to be aligned in order to scan quickly and effectively.
Finally, Thanks to the person who provided this source for solving my many problems.

**Comment by bero93** [comment]
> @saddem123 You can fork this library, make the changes you need and then point to your fork in the pubspec.yaml, e.g.
> 
> ```
> barcode_scan:
>     git: 
>       url: [your_fork]
> ```

non related question : how to do the same functionality if i want to replace a flutter core widget with a custom one made by me

**Comment by AlexHartford** [comment]
Any updates on this? Would like to adopt this but is basically unusable without being able to embed the scanner view into our own widget.

**Comment by Sandro-darli** [comment]
Hello! We already have a solution to change hide the title?

**Comment by saddemYassin** [comment]
Hello sorry for answering so late I'm not using this email in the last
period.

The problem was solved for a long time now 2 months.

thank you and sorry again.

**Comment by krupeshxebia** [comment]
I read the entire thread, still not sure how to customize scanner ui. Using Flutter,  No knowledge of Kotlin. Any step by step guide would be very helpful :)

**Comment by xi1570-krupeshanadkat** [comment]
@devtronic just marking the 10-15 issues closed and bringing everyone on same thread won't help. How about some solution?

**Comment by devtronic** [comment]
How about some solution?! This is an open source project so feel free to contribute!

**Comment by xi1570-krupeshanadkat** [comment]
> How about some solution?! This is an open source project so feel free to contribute!

 @devtronic modified readme for Custom Title, created PR. Could you help me know where in source code we have colors defined (for scanning rectangle)?? I would be happy to help put some info in readme for everyone.

**Comment by xi1570-krupeshanadkat** [comment]
@saddem123 Solution to your issue, (for Android)
add these lines in android/app/src/main/AndroidManifest.xml after `</activity>` tag
```xml
<activity 
          android:name="de.mintware.barcode_scan.BarcodeScannerActivity"
          android:theme="@android:style/Theme.Black.NoTitleBar" />
```
This will remove title bar (app bar) in the scanning screen.

To just change the title use below:
```xml
<activity 
     android:name="de.mintware.barcode_scan.BarcodeScannerActivity"
     android:label="My Activity Title" />
```
(Replace "My Activity Title" with your desired title)

**Comment by bhammer88** [comment]
Would be a great help even we can modify the the outline colors to match out app design theme. Of course overlaying will give us more customisation.

**Comment by kamleshwebtech** [comment]
> @saddem123 Solution to your issue, (for Android)
> add these lines in android/app/src/main/AndroidManifest.xml after `</activity>` tag
> 
> ```
> <activity 
>           android:name="de.mintware.barcode_scan.BarcodeScannerActivity"
>           android:theme="@android:style/Theme.Black.NoTitleBar" />
> ```
> 
> This will remove title bar (app bar) in the scanning screen.
> 
> To just change the title use below:
> 
> ```
> <activity 
>      android:name="de.mintware.barcode_scan.BarcodeScannerActivity"
>      android:label="My Activity Title" />
> ```
> 
> (Replace "My Activity Title" with your desired title)

Dear, i do not want to remove scan screen appbar, just want to change background color of app bar, please suggest how can we do? Thanks.
